### ISSUE TITLE
Set up Linting with Black

### ISSUE THREAD

**Issue by orioncohen** [MDAnalysis/solvation-analysis#10]
I'm going to be using [Black](https://github.com/psf/black) for this project and I would like to learn to set up Linting for a GitHub repo

**Comment by hmacdope** [comment]
Re linting using an automated bot in the CI matrix is a good step. Other than that you can use pre-commit hooks, but I have personally never been bothered enough.
This is an auto black linter some people seem to use
https://github.com/marketplace/actions/black-code-formatter
