### ISSUE TITLE
Unpin scipy

### ISSUE THREAD

**Issue by tsmathis** [MDAnalysis/solvation-analysis#106]
Scipy is currently pinned at `1.12.0` which is causing some difficulty updating dependencies in down stream packages ([emmet-core #1020](https://github.com/materialsproject/emmet/issues/1020))

Is `1.12.0` specifically needed here? Is a `>=` option viable?

**Comment by hmacdope** [comment]
@orionarcher can you remember why this pin exists again?

**Comment by orionarcher** [comment]
Thank you to hmacdope and richard for fixing the issue. I can mint a new release soon.

**Comment by tsmathis** [comment]
thanks orion :)
