### ISSUE TITLE
Finalize and develop tutorial

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#13]
Final proposed goal for GSOC:

From proposal:

"Finalize selection and analysis functions. Develop a thorough tutorial within a jupyter
notebook to teach the solvation module to new users"

**Comment by orioncohen** [comment]
@IAlibay mentioned in PR #29 that it would be useful to add usage examples to the in-line docs. I am going to work on that when addressing this issue.
