### ISSUE TITLE
Possible enhancements to capped-distances

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#14]
If time allows we MAY look at implementing the `n_closest_neighbours` algorithm using the `capped distances` library.

This is a stretch goal.

**Comment by hmacdope** [comment]
This is being addressed by @richardjgowers upstream.

**Comment by orioncohen** [comment]
This is now out of scope, closing.

**Comment by hmacdope** [comment]
Roger that.
