### ISSUE TITLE
Complete get_n_shells / generalize identify solvation cutoff

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#19]
The `get_n_shells` function should be completed once we are happy with the design and signatures for `get_closest_n_mols`

**Comment by hmacdope** [comment]
Have we completed this @orioncohen? I have kinda lost track. If so please close.

**Comment by orioncohen** [comment]
This is still open! I think this is going to be quite challenging to implement well. Before tackling this I'll need to improve the solvation cutoff kernel, which if I am being honest, kinda sucks right now.

**Comment by hmacdope** [comment]
At least your honest :)

**Comment by orioncohen** [comment]
I no longer have plans to implement this functionality. I now believe that finding a good cutoff for the 2nd+ solvation shell is too situational to implement effectively in this sort of "one-size-fits-all" package. If others have ideas, I'm all ears, but its no longer on my radar so I am closing :)

**Comment by hmacdope** [comment]
Yep sounds good.
