### ISSUE TITLE
Add type hinting to solvation selection functions

### ISSUE THREAD

**Issue by orioncohen** [MDAnalysis/solvation-analysis#23]
I think that type hints could be useful here. Any preference from the core devs?

**Comment by lilyminium** [comment]
In the future, you can ping coredevs with @MDAnalysis/coredevs for those who might not watch this repo :-)

I personally like type hints but I'm not entirely sure how far you can get in 3.6 with them wrt stuff like numpy arrays. I guess one freedom of MDAKits might be that you can restrict your supported Python versions to a subset of the core package?

**Comment by jbarnoud** [comment]
I do like type hinting and I use it extensively at work. However, for type hinting to be really useful in MDAnalysis, it must type-hint numpy arrays, which is only really possible with very recent versions of numpy. I did not look at the code here, but type-hinting arrays may be less critical; otherwise, it might be an interesting test ground if we agree on MDAkits having more stringent version requirement than the core library.

**Comment by hmacdope** [comment]
I would be all for type hinting, In general, I think we should get ahead of the curve on type hinting.

**Comment by IAlibay** [comment]
Here's my 2 cent on things.

### Python & Numpy versions in MDAKits

> I guess one freedom of MDAKits might be that you can restrict your supported Python versions to a subset of the core package?

and

> if we agree on MDAkits having more stringent version requirement than the core library

Assuming we need to be able to check cross-MDAKit and upstream compatibility, I think we're going to have to enforce that MDAKits adhere to NEP29. MDAKits that breach this can certainly exist, but trying to work out the one python & numpy version that works is too large a requirement on whatever CI pipeline we'll need to build here.

### Type hinting

If you can make it work within the constraints of NEP29, then I support the idea. That being said, I don't think it should be a project priority, i.e. faster progress towards creating code that meets project goals >> type hinting.

**Comment by hmacdope** [comment]
I think we can close this for now.
