### ISSUE TITLE
Fix the badges in the README

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#3]
The badges in the readme are not displaying properly. Should be able to be fixed so that they display mostly correctly. The best guide for which badges are the ones on the MDA core repo README

**Comment by orioncohen** [comment]
Hmm, not quite sure what's going on here. Tried copy and pasting the same formatting of the badges as in the core repo but that's still displaying incorrectly. I'll do some more digging.

**Comment by hmacdope** [comment]
I'll see if I can get the right resource link :).
