### ISSUE TITLE
Add tiled rdf plots

### ISSUE THREAD

**Issue by orionarcher** [MDAnalysis/solvation-analysis#30]
@hmacdope suggested creating a function to plot all rdf's as subplots in one figure

**Comment by samueldyoung29ctr** [comment]
I just cloned the repo and see that `Solute._plot_solvation_radius` is creating its own Matplotlib figure and axes objects. If you're still interested in tiled plots, I think a more flexible solution would be another method that imperatively plots on an axes handle the user provides. Something like

```python
class Solute(AnalysisBase):

    ...

    @staticmethod
    def _plot_solvation_radius(bins, data, radius, ax):
        """
        Plot a solvation radius on an RDF.

        Includes a vertical line at the radius of interest.

        Parameters
        ----------
        bins : np.array
            the RDF bins
        data : np.array
            the RDF data
        radius : float
            the cutoff radius to draw on the plot
        ax : matplotlib.axes.Axes

        Returns
        -------
        
        """
        ax.plot(bins, data, "b-", label="rdf")
        ax.axvline(radius, color="r", label="solvation radius")
        ax.set_xlabel("Radial Distance (A)")
        ax.set_ylabel("Probability Density")
        ax.legend()
```

Then you don't have to handle any of the ncols, nrows, etc. options for `matplotlib.pyplot.subplots`.

**Comment by orionarcher** [comment]
Thanks for the suggestion!

I intend to migrate to `plotly` eventually and I'll consider this UI approach when I do. 

If you are inclined to open a PR, that'd be welcome!
