### ISSUE TITLE
make solute also be able to be a solvent

### ISSUE THREAD

**Issue by orionarcher** [MDAnalysis/solvation-analysis#31]
In the case of large molecules with a specific atom or residue solvated, it might be necessary to treat part of the molecule as a solvent and part as a solute. Right now, I believe that will break solvation_analysis. I am creating this issue as a reminder to investigate the issue.

**Comment by orioncohen** [comment]
This should be a default. This could cause issues in heavily concentrated solutions.

**Comment by orionarcher** [comment]
Solved by PR #70, closing.
