### ISSUE TITLE
Pip release of 0.0.1

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#34]
We should release 0.0.1 on pip before the end of GSOC. It can always be improved later.

**Comment by IAlibay** [comment]
Just an FYI here, semver does support the idea of 0.1.0 being the first release (0.0.1 is essentially saying you've got a bug fix from version 0.0.0). If you're aiming for the spirit of an alpha release then 0.0.1 still makes sense.

**Comment by orioncohen** [comment]
Should I be using [versioneer](https://github.com/warner/python-versioneer/blob/master/INSTALL.md#post-installation-usage) for release management?

The current functionality is pretty solid, so I'd be inclined to release under 0.1.0!

**Comment by hmacdope** [comment]
Yes you should use versioneer! It's very useful, please make an issue and seperate PR. 

I would hold an 0.1.0 release until #36 is merged if thats okay? Feel free to test on PyPi using the test [server](https://test.pypi.org/)

**Comment by orioncohen** [comment]
I think we are good to release here! I am going to put this out on pip tomorrow! Anything else that needs to happen before release?

**Comment by hmacdope** [comment]
You should add a new tag now that #36 has been merged, as your tagged version is at `0c38a435bd7fc98e1504f370e3bd5e744c35dc10` and the current main is at `b9db52d613edbb9bface1ab3b30f63f689870cf8 `.

**Comment by hmacdope** [comment]
Note that rather than  something like "initial release" use something related to the semver tag name as it's easier to follow.

You can also use something like the name `v0.1.1-alpha` and `pre release` option if you would like to play with installing a version on pip before making possible changes in an `v0.1.1-alpha.1` pre release and then releasing `v0.1.1` in due course.

**Comment by orioncohen** [comment]
I should have taken your advise with the -alpha tag but I put it on test-pypi as v0.1.1. 

One issue I am having, when I install from pip the requirements are not being automatically installed along with the main package, so I immediately encounter import errors. How can I enforce the automatic installation of requirements?

**Comment by orioncohen** [comment]
Additionally, once I do get all the requirements installed I am getting a `ModuleNotFoundError: No module named 'solvation_analysis'` error...

I tried pip installing in a fresh conda environment so I am not sure what the issue is.

**Comment by orioncohen** [comment]
When I call `python setup.py sdist bdist_wheel` the build nearly completes but then throws an error:
`UPDATING solvation_analysis-0.1.1b1/solvation_analysis/_version.py
error: [Errno 2] No such file or directory: 'solvation_analysis-0.1.1b1/solvation_analysis/_version.py'`

If I then copy past _version.py into the directory it is missing from and re-run `python setup.py sdist bdist_wheel`, it works fine. Just slightly annoying that it doesn't get copied in. Not sure how to fix.

**Comment by orioncohen** [comment]
Hot off the press! [Version 0.1.1](https://pypi.org/project/solvation-analysis/)!

**Comment by orioncohen** [comment]
Now just to write some blog posts

**Comment by hmacdope** [comment]
I take it from your last few comments that you resolved your issues?

If so please close issue 😃.  And yay blogging! 

I will also try out the pip version today on my box.

**Comment by orioncohen** [comment]
I didn't resolve the last issue, but that's more of an inconvenience. Anyway, closing! Yay!

**Comment by hmacdope** [comment]
It works on my setup just for the record.
