### ISSUE TITLE
Tag not merged.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#38]
@orioncohen, whatever tag you put on your versioneer branch has not merged. Try adding a tag on the front page on github and pulling, or adding on command line of `main` and pushing.

**Comment by orioncohen** [comment]
How will I know when this has been successful?

**Comment by hmacdope** [comment]
Tags will be visible on the github home page, right next to where it says `main`, currently says 0 tags.

**Comment by orioncohen** [comment]
I added a tag through GitHub, closing!
