### ISSUE TITLE
Set up docs.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#4]
When we have some docs ready to build (requires some docs and a `readthedocs.yaml`) they will be built at https://solvation-analysis.readthedocs.io/en/latest/. When ready we should set the repo up to build docs correctly.

**Comment by orioncohen** [comment]
What will we need to do to set up the repo? I imagine this should wait until some base functionality is implemented so that we have actual documentation to build?

**Comment by lilyminium** [comment]
https://solvation-analysis.readthedocs.io/en/latest/ is actually up and has the template docs :)

**Comment by hmacdope** [comment]
Yeah not urgent until we have actual code. :)

I think we just need to make a 'readthedocs.yaml' and point the sidebar URL to the right one.

There is no particular order to issues. Some things may be far in the future. Just deal with them in whatever order works for you :)

**Comment by hmacdope** [comment]
Skeleton docs are now being built! Well done. I'll close this now.

**Comment by orioncohen** [comment]
Hey It looks like the docs aren't being properly constructed at [https://solvation-analysis.readthedocs.io/en/latest/](https://solvation-analysis.readthedocs.io/en/latest/). What am I missing here to get these displaying properly?

**Comment by lilyminium** [comment]
I'm not sure what you mean, I can see built docs?

![image](https://user-images.githubusercontent.com/31115101/123186915-0288f600-d44e-11eb-9d6f-8c7b2bcba491.png)

**Comment by orioncohen** [comment]
Oop . Maybe it was a mistake to expect it to be automatically populated with documentation :). I'll close this again and work on writing content to the docs instead.
