### ISSUE TITLE
Conda release in the future.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#42]
Not to be done before the end of GSOC, but we can also do a release of solvation-analysis on conda-forge.  This can be a little bit involved, see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html) for guide.  Lets look at this a bit down the track.

**Comment by hmacdope** [comment]
@orionarcher we should probably do this before the JOSS submission? Easy install is always a bonus.
I have made a few conda packages so happy to help, but its actually pretty fun to make a conda recipe so ill leave it to you.

**Comment by orionarcher** [comment]
Sounds good. I'll take a swing at it and tag you if I have any problems.

**Comment by orionarcher** [comment]
I created a PR to conda-forge [here](https://github.com/conda-forge/staged-recipes/pull/21785). I'll close this when it's merged!

**Comment by hmacdope** [comment]
Congrats @orionarcher on the conda package. :)

**Comment by orionarcher** [comment]
wheeeeee :)
