### ISSUE TITLE
Reliably handle multi-atom solutes

### ISSUE THREAD

**Issue by orionarcher** [MDAnalysis/solvation-analysis#47]
Currently, solvation_analysis has fairly weak support for multi-atom solutes. The implications of multi-atom solutes have not been well-considered and could be inaccurate. A thorough audit is needed to ensure the reliability of results. It would be useful to add a test example with a multi-atom solute.

**Comment by hmacdope** [comment]
Where do we think the main point of failure is? RDF cutoff (solvation radius) identification or something else? I guess we wont know without a test.

**Comment by orioncohen** [comment]
Unfortunately, I don't think this is a simple problem. Even if we had a perfect RDF cutoff function, that would still only work for small, mostly symmetric solutes because it would have to calculate a cutoff from the center of mass.

I think that a better solution might be to allow the user to supply a **list** of solute AtomGroups that are each different atoms in the same molecule. Each atom would calculate its own RDF and find its own solvation shell and then that data would be aggregated into a single solvation_data object. That would be extensible to large and fairly heterogenous molecules, though it might be slow. 

There also might be a way to do that behind the scenes, but that can come later.

I think this would also require dealing with issue #43.

**Comment by orionarcher** [comment]
After some thought, I believe the best way to approach this is to implement some sort of `AggregateSolution` functionality (name is a work in progress). This could be instantiated from several solutions and would merge together all of the `solvation_data` by their residue id, then rerun all of the analysis functionality. This would allow one to find the "coordination number" or other properties around a large and complex molecule. It would also allow a good amount of flexibility by letting the user create several `Solution` objects for different functional groups with different parameters, then merge them into a single object.

This will also require solving issue #31, where if something is a solute it cannot also be a solvent. There are many cases where a solute might coordinate with itself.

There is also a case where a user might want to include several identical atoms as solutes in a single `Solution`. This is currently not supported and should be considered a bug. This must also be fixed before we can implement the changes proposed here.

Imagine we have acetic acid dissolved in water. The user would first create three `Solution` objects for the ketone, alcohol, and methyl groups:

python
```
u = Universe(...)

water = u.atoms.select_atoms(...)
acetic_acid = u.atoms.select_atoms(...)
ketone = u.atoms.select_atoms(...)
alcohol = u.atoms.select_atoms(...)
methyl = u.atoms.select_atoms(...)

solvents = {"H2O": water, "acid": acetic_acid}

ketone_solution = Solution(ketone, solvents)
alcohol_solution = Solution(alcohol, solvents)
methyl_solution = Solution(methyl, solvents)
```

We would then instantiate the `AggregateSolution` from the three solutions. We could then treat this like any other solution object. This allows us to re-use the same api and functionality with only minimal setup required from the user.

python
```
agg_solution = AggregateSolution([ketone_solution, alcohol_solution, methyl_solution])

agg_solution.pairing # calculated on residue index
agg_solution.speciation # calculated on residue index
agg_solution.coordination # calculated on residue index

agg_solution.solutions # access the child solutions
```

Would love to hear feedback on this approach @hmacdope @rkingsbury. Happy to provide more context or details.

**Comment by hmacdope** [comment]
This approach sounds good to me! The more code reuse we can get out of the API we already have the better. 

As you pointed our solving #31 is a priority. I will raise an issue for the "identical atoms" case you mentioned as well. 

We should do some testing on some more data to make sure the results seem reasonable as I think it would be easy to introduce some hard to find complications when doing large merges on the `pandas` data. 

For some extra fancyness you could even do operator overloading on the `Solution` object like so 

```python
agg_solution = ketone_solution + alcohol_solution + methyl_solution
```

Once we get these sorted out I think we will be close to a polished release as this was the last of the stuff on the 1.0 roadmap!

**Comment by orionarcher** [comment]
> We should do some testing on some more data to make sure the results seem reasonable as I think it would be easy to introduce some hard-to-find complications when doing large merges on the pandas data.

Agreed, new testing will be critical. I'm working to get some new data for a test system. I plan to upload a test system where the solute has i) multiple functional groups and ii) some functional groups have multiple identical atoms, which will allow us to address issues #31 and #66. Currently, all test systems are Li-ion electrolytes, which aren't appropriate for addressing either issue.

I'll think if there's a clean way to implement this with a binary operator to enable overloading. That would super cool to have.
