### ISSUE TITLE
Formalize Roadmap in Projects tab

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#48]
We should decide on a model for a release schedule, Do we wish to match the MDA core idea and do quarterly (@IAlibay  is that right?) releases? Or do we just want to do with major functionality change, ie at your discretion @orioncohen?

If people want updated functionality and bugfixes, they can always clone the current `main` branch and install with `pip install -e .`

Raising issue as food for thought.

**Comment by orioncohen** [comment]
Thanks for raising this @hmacdope! For now, I think I'd prefer to keep the releases relatively frequent. My (unordered) roadmap is roughly this:

- Deal with issues #31, #43, #46, and #47 
- Finish PR #40
- Ensure tutorials cover all features
- Finalize names of existing features

Once those things are done, I think it will be time to cut a 0.2 release and I'd be happy to reconsider shifting to a quarterly release schedule.

Does that sound reasonable? 

Also, would the Projects tab be the best place to lay out that roadmap? I feel like I should formalize it somewhere.

**Comment by hmacdope** [comment]
That looks great to me! Great idea to formalise in a roadmap.

Lets use the projects tab! Kanaban with automation is the projects card format I chose last time and it seems to be quite good. I leave it to you to setup?

**Comment by IAlibay** [comment]
>  Do we wish to match the MDA core idea and do quarterly (@IAlibay is that right?) releases?

The exact release schedule for MDA hasn't been agreed. I _think_ we'll be moving towards maximum quarterly, but as with everything, if we think a version needs to be out faster then we'll do that.

My 2 cents here - don't try to match the MDA release schedule. That would completely break the idea of having downstream analysis packages that are dissociated from the main MDA package. MDA is mature code that will move slowly but also break very few things (hopefully) between versions. It's very unlikely that you would see any impacts on solvation-analysis between 2.0.0 and 2.1.0. I would instead just focus on doing releases at a frequency that is required by your user base to account for any new features and/or bugs that might occur.

Once the codebase has reached maturation then you can start thinking about more scheduled releases (keeping up with things like NEP29, etc...).

**Comment by hmacdope** [comment]
Thanks for that @IAlibay, makes a lot of sense.  I think we go with "at your discretion" then @orioncohen

**Comment by orioncohen** [comment]
Sounds great to me! Thank you for your input @IAlibay. I'm going to change this issue to "Formalize Roadmap in Projects tab" and close it when I have done that.

**Comment by orioncohen** [comment]
I've just added a roadmap and cleaned up the issues page.

My semester here is wrapping up so I'll have more time to put into solvation-analysis. My plan is to try and finish the goals in the v0.2 roadmap over the holiday break. After that, I'd like to draft a JOSS submission. Happy to discuss more when the time comes!

**Comment by hmacdope** [comment]
Sounds fantastic! I am fully on board with that idea. I will also put some hours in myself. Anything you want me to prioritise feel free to assign me to an issue etc etc.

**Comment by orioncohen** [comment]
Will do! Once I get some PRs up I'll be requesting review too.
