### ISSUE TITLE
Add additional notebook showing use of custom RDF parser function

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#54]
We should provide an example of how to use a custom function to identify RDF critical points.
I have two examples, one with `scipy.find_peaks()` and another using a trained `pytorch` model.

I will add them to the `rdf_fitting_demo` notebook. :)

**Comment by orioncohen** [comment]
Ok that sounds great, I am excited to see how they work! If either works well, I think we should replace the default kernel.

**Comment by hmacdope** [comment]
PyTorch one dropped for now, too complex and not performing as I want.

**Comment by hmacdope** [comment]
Closed as part of #56
