### ISSUE TITLE
Have identical atoms as solutes in a single Solution.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#66]
Currently we do not allow include identical atoms to be solutes in a single Solution. 

This is quite a common use case and is a blocker for #47.

**Comment by orionarcher** [comment]
To clarify from my comment in #47. This is an issue with several identical atoms in a single residue. For example, if I wanted to explore the solvation of 50 Li+ atoms that are all distinct residues, that's not an issue. 

If, however, I wanted to explore the solvation around both O in ethylene glycol, that could present issues. It would be natural to include all the identical O in a single Solution, but that would require two Solute atoms in a single residue, which is not well supported.

![image](https://user-images.githubusercontent.com/27712051/179424417-0f4ec225-3357-44e9-be22-8fdb5f8eff02.png)

**Comment by orionarcher** [comment]
I have decided to not allow this behavior since the new multi-atom solute changes will provide a good alternative. Closing now.
