### ISSUE TITLE
Work towards MDAKit integration

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#68]
Now that MDAKits are live to roll we should work towards registering `solvation-analysis` as an MDAKit!

See the [blog post](https://www.mdanalysis.org/2022/08/24/mdakits-intro/) for more info. 

@orionarcher  I would be interested to know if you would prefer to just go for it or wait for `0.2.0` (and some conda packages). 

AFAIK `solvation-analysis` already meets all the requirements listed in the [white paper](https://figshare.com/articles/preprint/MDAKits_Supporting_and_promoting_the_development_of_community_packages_leveraging_the_MDAnalysis_library/20520726/1).

**Comment by hmacdope** [comment]
Ok no rush, registry not here yet.

**Comment by orionarcher** [comment]
I'd say let's hold off for version 0.2.0, I want to prioritize that before registering.

**Comment by orbeckst** [comment]
@orionarcher Can you register the kit before the [UGM at the end of September](https://www.mdanalysis.org/pages/ugm2023/)? It would make for a nice show case and would really help us to demonstrate the MDAKits ecosystem.

The process is not difficult: https://mdakits.mdanalysis.org/add.html (and there's a longer version in the [making an mdakit tutorial](https://mdakits.mdanalysis.org/makingakit.html).

**Comment by orionarcher** [comment]
Yep no problem! Thanks for the links.

**Comment by orionarcher** [comment]
PR open here: https://github.com/MDAnalysis/MDAKits/pull/67, let me know how it looks!

**Comment by orbeckst** [comment]
Any chance you could look at #93 ? Or at least pin your conda recipe and make increment your build number and update your source deps https://github.com/MDAnalysis/solvation-analysis/blob/055cbd9272c9005286a58e3ac0ac95da7ca6673f/pyproject.toml#L32 ?
