### ISSUE TITLE
Replace `solvation_data_dup` data frame with only the duplicates

### ISSUE THREAD

**Issue by orionarcher** [MDAnalysis/solvation-analysis#71]
right now we double the memory footprint of `solvation_data` by also storing `solvation_data_dup`. We should store only the redundant entries instead.

**Comment by hmacdope** [comment]
Might be good to add a method to check how much memory we are actually using in the DF. This may be useful https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.memory_usage.html

**Comment by orionarcher** [comment]
Probably a good idea. I'll look into adding that later. For now, this was closed by PR #70.
