### ISSUE TITLE
Concatenation Issue for Residence Time Calculation

### ISSUE THREAD

**Issue by SophiaRuan** [MDAnalysis/solvation-analysis#81]
I am using `Residence.from_solute(solute)` to calculate the residence time between trimers' N and water' O. It always reports the same concatenation issue which seems to be caused by the calculation of auto-covariance (Fig 1). However, when I calculate the residence time between anion and water, there isn't this problem. I add the solvation_data of anion solution (Fig 2) and trimer solution for your reference (Fig 3). 

<img width="1022" alt="Screen Shot 2022-12-05 at 15 58 01" src="https://user-images.githubusercontent.com/67963337/205772142-360f614e-cfb8-461b-b927-c612850ed424.png">
<img width="1109" alt="Screen Shot 2022-12-05 at 15 58 21" src="https://user-images.githubusercontent.com/67963337/205772141-80224d2d-7a1d-4668-8a5e-b5cbdaf8e73d.png">Fig 1

<img width="549" alt="Screen Shot 2022-12-05 at 15 53 21" src="https://user-images.githubusercontent.com/67963337/205773198-5d0cfee1-7f53-43a6-8ff5-2ab0be54a611.png">
Fig 2

<img width="583" alt="Screen Shot 2022-12-05 at 15 52 53" src="https://user-images.githubusercontent.com/67963337/205771207-8d3e463f-9c35-4b9e-96fc-1608fde7e63a.png">Fig 3

**Comment by hmacdope** [comment]
@orionarcher I will close as adressed via #82
