### ISSUE TITLE
Release prior to JOSS paper

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#84]
We should likely do a release prior to the JOSS paper both for #82 and to make a conda-forge package from it #42 once its on PyPi

**Comment by hmacdope** [comment]
It always looks nicer when the commit for the joss paper is a nice tag.

**Comment by orionarcher** [comment]
Agreed. I'd like to put out v0.2 prior to release. @laurlee will be finishing up some basic plotting in PR #67 soon and then I'll mint the new release. I think everything else is in pretty good shape.

**Comment by orionarcher** [comment]
@hmacdope would you like me to add you as a maintainer for the conda-force package?

**Comment by hmacdope** [comment]
Cheers, I think that would be a good idea, good to have more than one maintainer. :)

**Comment by hmacdope** [comment]
You will have to tag me in a comment on the 'staged recipies' PR  so that I can give my permission.

**Comment by orionarcher** [comment]
Agreed :) 

PR is [here](https://github.com/conda-forge/staged-recipes/pull/21785)! Just tagged you.

**Comment by orionarcher** [comment]
Released v0.2.0 and submitted!
